### PR TITLE
Add vanilla js PeriodicalQuery fallback

### PR DESCRIPTION
**Pull request by emilos**
Hey :)

thanks for the lib :+1: . I've added a fallback so that it works in envs where there's no $ plus added a possibility to add additional attributes to the script tag. This should help with https://github.com/pelargir/auto-session-timeout/issues/16

### CODE REVIEW

**Comment by pelargir** [comment]
This looks good. I'm actually thinking we should just use the vanilla implementation and remove the library-specific code completely. I can't think of a reason to keep the library-specific code around if the vanilla implementation works. Would you mind updating the PR to do that?

**Comment by emilos** [comment]
@pelargir no worries :) I'll take care of this later today

**Comment by emilos** [comment]
@pelargir done, please have a look again

**Comment by pelargir** [comment]
Very nice. Merging.

**Pull request merged**
